version: '3.9'
services:
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@host.docker.internal:5432/evolution?schema=public
      - CACHE_REDIS_URI=redis://redis:6379/6

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  evolution_instances:
  redis_data: