# Generated by Django 5.2.6 on 2025-09-24 12:01

import common.models
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantContextFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Nome descritivo para identificar o arquivo', max_length=255, verbose_name='Nome do arquivo')),
                ('file', models.FileField(help_text='Arquivo a ser usado como contexto', upload_to='assistant_context/', verbose_name='Arquivo')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Texto'), ('docx', 'Word'), ('md', 'Markdown'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML'), ('jpg', 'Imagem JPEG'), ('png', 'Imagem PNG'), ('gif', 'Imagem GIF'), ('webp', 'Imagem WEBP')], max_length=10, verbose_name='Tipo do arquivo')),
                ('extracted_content', models.TextField(blank=True, help_text='Texto extraído do arquivo para usar como contexto', null=True, verbose_name='Conteúdo extraído')),
                ('status', models.CharField(choices=[('uploading', 'Enviando'), ('processing', 'Processando'), ('ready', 'Pronto'), ('error', 'Erro')], default='uploading', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de erro')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do arquivo (bytes)')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, o arquivo não será incluído no contexto', verbose_name='Ativo')),
                ('openai_file_id', models.CharField(blank=True, help_text='ID do arquivo na OpenAI Files API (para PDFs)', max_length=255, null=True, verbose_name='OpenAI File ID')),
            ],
            options={
                'verbose_name': 'Arquivo de Contexto',
                'verbose_name_plural': 'Arquivos de Contexto',
                'ordering': ['-created_at'],
            },
            bases=(common.models.HistoryMixinSave, models.Model),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='ID da Sessão')),
                ('message', models.JSONField(help_text='Estrutura JSON contendo mensagens do humano ou da IA', verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('closed', models.BooleanField(default=False, help_text='Indica se a sessão foi encerrada', verbose_name='Sessão Encerrada')),
                ('type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('web', 'Web'), ('other', 'Outro')], default='whatsapp', max_length=20, verbose_name='Canal de Origem')),
                ('external_id', models.CharField(blank=True, help_text='ID de referência em sistema externo (ex: WhatsApp, CRM, n8n)', max_length=255, null=True, verbose_name='ID Externo')),
            ],
            options={
                'verbose_name': 'Histórico de Chat',
                'verbose_name_plural': 'Históricos de Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssistantContextFile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Nome descritivo para identificar o arquivo', max_length=255, verbose_name='Nome do arquivo')),
                ('file', models.TextField(help_text='Arquivo a ser usado como contexto', max_length=100, verbose_name='Arquivo')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Texto'), ('docx', 'Word'), ('md', 'Markdown'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML'), ('jpg', 'Imagem JPEG'), ('png', 'Imagem PNG'), ('gif', 'Imagem GIF'), ('webp', 'Imagem WEBP')], max_length=10, verbose_name='Tipo do arquivo')),
                ('extracted_content', models.TextField(blank=True, help_text='Texto extraído do arquivo para usar como contexto', null=True, verbose_name='Conteúdo extraído')),
                ('status', models.CharField(choices=[('uploading', 'Enviando'), ('processing', 'Processando'), ('ready', 'Pronto'), ('error', 'Erro')], default='uploading', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de erro')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do arquivo (bytes)')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, o arquivo não será incluído no contexto', verbose_name='Ativo')),
                ('openai_file_id', models.CharField(blank=True, help_text='ID do arquivo na OpenAI Files API (para PDFs)', max_length=255, null=True, verbose_name='OpenAI File ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Arquivo de Contexto',
                'verbose_name_plural': 'historical Arquivos de Contexto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLLMProviderConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('display_name', models.CharField(default='Configuração LLM', help_text="Nome para identificar esta configuração (ex: 'OpenAI GPT-4 - Suporte')", max_length=100, verbose_name='Nome da Configuração')),
                ('name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google DeepMind'), ('mistral', 'Mistral AI'), ('cohere', 'Cohere'), ('meta', 'Meta (LLaMA)'), ('xai', 'xAI (Grok)'), ('other', 'Outro')], default='openai', max_length=50, verbose_name='Fornecedor LLM')),
                ('model', models.CharField(help_text='Ex: gpt-3.5-turbo, claude-3, mistral-7b, etc.', max_length=100, verbose_name='Modelo')),
                ('instructions', models.TextField(blank=True, help_text='Prompt inicial ou system message', null=True, verbose_name='Instruções')),
                ('max_tokens', models.PositiveIntegerField(default=1024, verbose_name='Máximo de tokens')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperatura')),
                ('top_p', models.FloatField(default=1.0, help_text='Amostragem nuclear (nucleus sampling)', verbose_name='Top-p')),
                ('presence_penalty', models.FloatField(default=0.0, verbose_name='Penalidade de presença')),
                ('frequency_penalty', models.FloatField(default=0.0, verbose_name='Penalidade de frequência')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Configuração de LLM',
                'verbose_name_plural': 'historical Configurações de LLM',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('display_name', models.CharField(default='Configuração LLM', help_text="Nome para identificar esta configuração (ex: 'OpenAI GPT-4 - Suporte')", max_length=100, verbose_name='Nome da Configuração')),
                ('name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google DeepMind'), ('mistral', 'Mistral AI'), ('cohere', 'Cohere'), ('meta', 'Meta (LLaMA)'), ('xai', 'xAI (Grok)'), ('other', 'Outro')], default='openai', max_length=50, verbose_name='Fornecedor LLM')),
                ('model', models.CharField(help_text='Ex: gpt-3.5-turbo, claude-3, mistral-7b, etc.', max_length=100, verbose_name='Modelo')),
                ('instructions', models.TextField(blank=True, help_text='Prompt inicial ou system message', null=True, verbose_name='Instruções')),
                ('max_tokens', models.PositiveIntegerField(default=1024, verbose_name='Máximo de tokens')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperatura')),
                ('top_p', models.FloatField(default=1.0, help_text='Amostragem nuclear (nucleus sampling)', verbose_name='Top-p')),
                ('presence_penalty', models.FloatField(default=0.0, verbose_name='Penalidade de presença')),
                ('frequency_penalty', models.FloatField(default=0.0, verbose_name='Penalidade de frequência')),
            ],
            options={
                'verbose_name': 'Configuração de LLM',
                'verbose_name_plural': 'Configurações de LLM',
                'ordering': ['-created_at'],
            },
            bases=(common.models.HistoryMixinSave, models.Model),
        ),
    ]
