# Generated by Django 5.2.6 on 2025-09-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalllmproviderconfig',
            name='config_type',
            field=models.CharField(choices=[('finance', 'Financeiro'), ('calendar', 'Agenda'), ('general', 'Geral')], default='general', help_text='Define o contexto de uso desta configuração', max_length=20, verbose_name='Tipo de Configuração'),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='config_type',
            field=models.CharField(choices=[('finance', 'Financeiro'), ('calendar', 'Agenda'), ('general', 'Geral')], default='general', help_text='Define o contexto de uso desta configuração', max_length=20, verbose_name='Tipo de Configuração'),
        ),
    ]
