services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.7
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances: