# Generated by Django 5.2.6 on 2025-09-25 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Método de Pagamento',
                'verbose_name_plural': 'Métodos de Pagamento',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Método de pagamento (obrigatório para despesas)', null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod', verbose_name='Método de Pagamento'),
        ),
    ]
