# Generated by Django 5.2.6 on 2025-09-25 14:55

from django.db import migrations


def create_default_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model('finance', 'PaymentMethod')

    # Métodos de pagamento padrão (sem user para serem globais)
    default_methods = [
        {'name': 'PIX', 'description': 'Pagamento via PIX', 'is_default': True},
        {'name': 'Dinheiro', 'description': 'Pagamento em dinheiro'},
        {'name': 'Cartão de Débito', 'description': 'Pagamento com cartão de débito'},
        {'name': 'Cartão de Crédito', 'description': 'Pagamento com cartão de crédito'},
        {'name': 'Transferência Bancária', 'description': 'Transferência entre contas bancárias'},
        {'name': 'Boleto', 'description': 'Pagamento via boleto bancário'},
    ]

    for method_data in default_methods:
        PaymentMethod.objects.get_or_create(
            name=method_data['name'],
            user=None,  # Métodos globais
            defaults={
                'description': method_data['description'],
                'is_default': method_data.get('is_default', False),
                'is_active': True,
            }
        )


def reverse_default_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model('finance', 'PaymentMethod')
    PaymentMethod.objects.filter(user=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymentmethod_movement_payment_method'),
    ]

    operations = [
        migrations.RunPython(create_default_payment_methods, reverse_default_payment_methods),
    ]
