# Generated by Django 5.2.6 on 2025-09-25 15:05

from django.db import migrations


def create_payment_methods_for_existing_users(apps, schema_editor):
    """
    Cria métodos de pagamento padrão para todos os usuários existentes no sistema
    """
    User = apps.get_model('authentication', 'User')
    PaymentMethod = apps.get_model('finance', 'PaymentMethod')

    # Métodos de pagamento padrão
    default_payment_methods = [
        {
            "name": "PIX",
            "description": "Pagamento via PIX",
            "is_default": True
        },
        {
            "name": "Dinheiro",
            "description": "Pagamento em dinheiro"
        },
        {
            "name": "Cartão de Débito",
            "description": "Pagamento com cartão de débito"
        },
        {
            "name": "Cartão de Crédito",
            "description": "Pagamento com cartão de crédito"
        },
        {
            "name": "Transferência Bancária",
            "description": "Transferência entre contas bancárias"
        },
        {
            "name": "Boleto",
            "description": "Pagamento via boleto bancário"
        },
        {
            "name": "Cheque",
            "description": "Pagamento com cheque"
        },
        {
            "name": "Vale Alimentação",
            "description": "Cartão ou vale alimentação"
        },
        {
            "name": "Vale Refeição",
            "description": "Cartão ou vale refeição"
        }
    ]

    users = User.objects.all()
    total_users = users.count()
    total_methods_created = 0

    print(f"🔄 Criando métodos de pagamento padrão para {total_users} usuários existentes...")

    for user in users:
        user_methods_created = 0

        # Verificar se o usuário já tem métodos de pagamento
        existing_methods_count = PaymentMethod.objects.filter(user=user).count()

        if existing_methods_count == 0:
            # Criar métodos padrão para este usuário
            for method_data in default_payment_methods:
                payment_method, created = PaymentMethod.objects.get_or_create(
                    user=user,
                    name=method_data['name'],
                    defaults={
                        'description': method_data['description'],
                        'is_default': method_data.get('is_default', False),
                        'is_active': True
                    }
                )

                if created:
                    user_methods_created += 1
                    total_methods_created += 1

            if user_methods_created > 0:
                print(f"✅ Usuário {user.username}: {user_methods_created} métodos criados")
        else:
            print(f"ℹ️ Usuário {user.username}: já possui {existing_methods_count} métodos")

    print(f"🎉 Migração concluída! Total de {total_methods_created} métodos de pagamento criados.")


def reverse_payment_methods_for_existing_users(apps, schema_editor):
    """
    Remove métodos de pagamento padrão criados para usuários existentes
    """
    PaymentMethod = apps.get_model('finance', 'PaymentMethod')

    # Remover apenas métodos com nomes padrão
    default_method_names = [
        "PIX", "Dinheiro", "Cartão de Débito", "Cartão de Crédito",
        "Transferência Bancária", "Boleto", "Cheque",
        "Vale Alimentação", "Vale Refeição"
    ]

    deleted_count = 0
    for method_name in default_method_names:
        methods_to_delete = PaymentMethod.objects.filter(
            name=method_name,
            user__isnull=False  # Apenas métodos com usuário específico
        )
        count = methods_to_delete.count()
        methods_to_delete.delete()
        deleted_count += count

    print(f"🔄 Rollback: {deleted_count} métodos de pagamento removidos.")


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20250925_1155'),
        ('authentication', '0001_initial'),  # Dependência do modelo User
    ]

    operations = [
        migrations.RunPython(
            create_payment_methods_for_existing_users,
            reverse_payment_methods_for_existing_users
        ),
    ]
