# Generated by Django 5.2.6 on 2025-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20250925_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='icon',
            field=models.CharField(default='💳', help_text='Emoji ou ícone para o método de pagamento', max_length=50, verbose_name='Ícone'),
        ),
    ]
