# Generated by Django 5.2.6 on 2025-09-24 12:01

import common.models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Instância')),
                ('instance_name', models.CharField(max_length=100, unique=True, verbose_name='Nome no Evolution API')),
                ('base_url', models.URLField(verbose_name='URL Base do Evolution API')),
                ('api_key', models.CharField(max_length=255, verbose_name='Chave da API')),
                ('status', models.CharField(choices=[('disconnected', 'Desconectada'), ('connecting', 'Conectando'), ('connected', 'Conectada'), ('error', 'Erro')], default='disconnected', max_length=20, verbose_name='Status')),
                ('phone_number', models.CharField(blank=True, help_text='Número capturado automaticamente após o pareamento via QR Code', max_length=20, null=True, verbose_name='Número do WhatsApp')),
                ('profile_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Perfil')),
                ('profile_pic_url', models.URLField(blank=True, null=True, verbose_name='URL da Foto de Perfil')),
                ('last_connection', models.DateTimeField(blank=True, null=True, verbose_name='Última Conexão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL do Webhook')),
                ('ignore_own_messages', models.BooleanField(default=True, help_text='Se ativo, ignora mensagens enviadas pelo próprio número da instância', verbose_name='Ignorar Mensagens Próprias')),
                ('authorized_numbers', models.TextField(blank=True, help_text='Lista de números autorizados separados por vírgula (ex: 5511999999999, 5511888888888)', null=True, verbose_name='Números Autorizados')),
                ('llm_config', models.ForeignKey(blank=True, help_text='Configuração do modelo de IA para esta instância', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.llmproviderconfig', verbose_name='Configuração LLM')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instância Evolution',
                'verbose_name_plural': 'Instâncias Evolution',
                'ordering': ['-created_at'],
            },
            bases=(common.models.HistoryMixinSave, models.Model),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=50, verbose_name='Número de origem')),
                ('to_number', models.CharField(max_length=50, verbose_name='Número de destino')),
                ('status', models.CharField(choices=[('ai', 'Atendimento por IA'), ('human', 'Atendimento humano'), ('closed', 'Encerrada')], default='ai', max_length=20, verbose_name='Status da sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('evolution_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='whatsapp_connector.evolutioninstance', verbose_name='Instância Evolution')),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvolutionInstance',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome da Instância')),
                ('instance_name', models.CharField(db_index=True, max_length=100, verbose_name='Nome no Evolution API')),
                ('base_url', models.URLField(verbose_name='URL Base do Evolution API')),
                ('api_key', models.CharField(max_length=255, verbose_name='Chave da API')),
                ('status', models.CharField(choices=[('disconnected', 'Desconectada'), ('connecting', 'Conectando'), ('connected', 'Conectada'), ('error', 'Erro')], default='disconnected', max_length=20, verbose_name='Status')),
                ('phone_number', models.CharField(blank=True, help_text='Número capturado automaticamente após o pareamento via QR Code', max_length=20, null=True, verbose_name='Número do WhatsApp')),
                ('profile_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Perfil')),
                ('profile_pic_url', models.URLField(blank=True, null=True, verbose_name='URL da Foto de Perfil')),
                ('last_connection', models.DateTimeField(blank=True, null=True, verbose_name='Última Conexão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL do Webhook')),
                ('ignore_own_messages', models.BooleanField(default=True, help_text='Se ativo, ignora mensagens enviadas pelo próprio número da instância', verbose_name='Ignorar Mensagens Próprias')),
                ('authorized_numbers', models.TextField(blank=True, help_text='Lista de números autorizados separados por vírgula (ex: 5511999999999, 5511888888888)', null=True, verbose_name='Números Autorizados')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('llm_config', models.ForeignKey(blank=True, db_constraint=False, help_text='Configuração do modelo de IA para esta instância', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agents.llmproviderconfig', verbose_name='Configuração LLM')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Instância Evolution',
                'verbose_name_plural': 'historical Instâncias Evolution',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('extended_text', 'Extended Text')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='whatsapp_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('audio_transcription', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('received_while_inactive', models.BooleanField(default=False, help_text='Indica se a mensagem foi recebida enquanto a instância estava inativa', verbose_name='Recebida com instância inativa')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_connector.chatsession')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_type', models.CharField(choices=[('n8n', 'n8n Webhook'), ('ai', 'AI Vision'), ('both', 'Both')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_connector.messagehistory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
