# Generated by Django 5.2.6 on 2025-09-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_connector', '0002_chatsession_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutioninstance',
            name='instance_evolution_id',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Id da Instância no Evolution API'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevolutioninstance',
            name='instance_evolution_id',
            field=models.CharField(db_index=True, default=1, max_length=100, verbose_name='Id da Instância no Evolution API'),
            preserve_default=False,
        ),
    ]
